version: "3.8"

services:
  database: 
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=database
      - POSTGRES_USER=database_ignite
      - POSTGRES_PASSWORD=docker1234
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes: 
  pgdata:
    driver: local